/// <reference types="cypress" />
describe('page', () => {
  it('works', () => {
    cy.visit('https://example.cypress.io')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    cy.get('.home-list')
    
    // Uncommenting the following will be enough to make the UI quite unresponsive when mousing in & out of the `.runnable-instruments` element
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
    // cy.get('.home-list')
  })
})
